// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unyyraykfzmlxrolyjpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVueXlyYXlrZnptbHhyb2x5anBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDAzODMsImV4cCI6MjA2Nzg3NjM4M30.456Ra8iiEJ4RYLyG79C7SoTEjgbFnkx0nsoIpB6yvz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});